# Template: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Build On Linux

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: |

        pip install conan==2.6.0

        conan profile detect

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |

        conan install . --build=missing

        cmake --preset thread-pool-sorter-release

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: cmake --build --preset thread-pool-sorter-release

    - name: Install Targets
      working-directory: ${{github.workspace}}
      run: |

        cmake --build --preset thread-pool-sorter-release -t install

    - name: Run Targets
      working-directory: ${{github.workspace}}
      run: |

        ./build/Release/snippet/StatDemo/StatDemo1 ./snippet/StatDemo/test.txt

        ./build/Release/snippet/StatDemo/StatDemo2 ./snippet/StatDemo/test.txt

        ./build/Release/snippet/ThreadPoolSorterDemo/ThreadPoolSorterDemo

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: install
        path: build/Release/install
        include-hidden-files: true
        if-no-files-found: error
