name: Unit Test On Linux

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Conan
      run: |

        pip install conan==2.6.0

        conan profile detect

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: |

        conan install . --build=missing

        cmake --preset thread-pool-sorter-release -DWITH_GTEST=ON

    - name: Build Targets
      working-directory: ${{github.workspace}}
      run: cmake --build --preset thread-pool-sorter-release

    - name: Run Unit Test
      working-directory: ${{github.workspace}}
      run: |

        cmake --build --preset thread-pool-sorter-release -t tests

        ./build/Release/test/gtest-testrun
